{
 "title": "IPFS Pinner",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values({job=~\"(.*/)?ipfs-pinner(-.*)?\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Component up status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"server-metrics\"})"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"worker-metrics\"})"
    }
   ]
  },
  { "title": "Server Metrics and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server status codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total{service=\"$service\"}[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Server logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*server.*\"}"
    }
   ]
  },
  {
   "title": "Server 4** by path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=\"$service\",status_code=~\"4.*\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Server 5** by path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=\"$service\",status_code=~\"5.*\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Worker metrics and logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Worker successful runs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_success{service=\"$service\"}[30m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Worker logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 14, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "{app=\"$service\",container_name=~\".*worker.*\"}"
    }
   ]
  },
  {
   "title": "Worker errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(worker_errors{service=\"$service\"}[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "File scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(file_scans{service=\"$service\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(irate(file_verified{service=\"$service\"}[5m]))",
     "legendFormat": "Verified"
    },
    {
     "expr": "sum(irate(file_expired{service=\"$service\"}[5m]))",
     "legendFormat": "Expired"
    }
   ]
  }
 ]
}